#библиотеки
library('e1071')     # SVM
library('ROCR')      # ROC-кривые
library('ISLR')      # данные по экспрессии генов


au <- Auto[,c('mpg', 'displacement', 'acceleration')]
high.mpg <- c(rep('Yes', nrow(au)))
high.mpg[au['mpg']<23] <- 'No'
au <- data.frame(au[,-1],high.mpg)

my.seed <- 1
n <- nrow(au)
train.percent <- 0.5
set.seed(my.seed)
inTrain <- sample(n, n * train.percent)


plot(x=au[inTrain, ]$acceleration, y=au[inTrain, ]$displacement,
     col = au[inTrain, ]$high.mpg, pch = 19)


# SVM с полиномиальным ядром и маленьким cost
svmfit <- svm(high.mpg ~ ., data = au[inTrain, ], kernel = "polynomial", 
              degree = 3, cost = 1)
plot(svmfit, au[inTrain, ])
summary(svmfit)

# SVM с полиномиальным ядром и большим cost
svmfit <- svm(high.mpg ~ ., data = au[inTrain, ], kernel = "polynomial", 
              degree = 3, cost = 1e5)
plot(svmfit, au[inTrain, ])
summary(svmfit)

# перекрёстная проверка
set.seed(1)
tune.out <- tune(svm, high.mpg ~ ., data = au[inTrain, ], kernel = "polynomial", 
                 ranges = list(cost = c(0.1, 1, 10, 100, 1000),
                               degree = 3))
summary(tune.out)

# матрица неточностей для прогноза по лучшей модели
table(true = au[-inTrain, "high.mpg"], 
      pred = predict(tune.out$best.model, newdata = au[-inTrain, ]))


# функция построения ROC-кривой: pred -- прогноз, truth -- факт
rocplot <- function(pred, truth, ...){
  predob = prediction(pred, truth)
  perf = performance(predob, "tpr", "fpr")
  plot(perf,...)}

# оптимальная модель
svmfit.opt <- svm(high.mpg ~ ., data = au[inTrain, ], 
                  kernel = "polynomial", degree = 3, cost = 100, decision.values = T)
# количественные модельные значения, на основе которых присваивается класс
fitted <- attributes(predict(svmfit.opt, au[inTrain, ],
                             decision.values = TRUE))$decision.values

# график для обучающей выборки
par(mfrow = c(1, 2))
rocplot(fitted, au[inTrain, "high.mpg"], main = "Training Data")


# график для тестовой выборки
fitted <- attributes(predict(svmfit.opt, au[-inTrain, ], 
                             decision.values = T))$decision.values
rocplot(fitted, au[-inTrain, "high.mpg"], main = "Test Data")

Оптимальный параметр 100. 
Машина опорных векторов неверно классифицирует 12% контрольных наблюдений.
